### ISSUE TITLE
Error when attempting to use octopilot in a Github Action

### ISSUE THREAD

**Issue by mattzech** [dailymotion-oss/octopilot#137]
Hello, we are trying to use octopilot to create a Pull Request to upgrade the version of a yaml file in our code. When the action begins, this is the error that we receive: 
```bash
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/tmp/actions-runner/_work/_actions/dailymotion-oss/octopilot/master'. Did you forget to run actions/checkout before running your local action?
```

Here is the action file:
```yaml
name: ocp-upgrade

on:
  issues:
    types:
      [opened, edited]

jobs:
  parse:
    runs-on: matt-ci
    steps:
      - uses: actions/checkout@v2
      - name: Pull Release Info
        shell: bash
        run: |
          file="$(curl https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/release.txt -o release.txt)"
          IMAGE="$(awk '/Pull From/{print $3}' release.txt)"
          VERSION="$(awk '/Version/{print $2;exit}' release.txt)"
          SHORT="${VERSION:0:4}"
      - uses: dailymotion-oss/octopilot@master
      - name: Run octo command
        run: |
          octopilot \
           ... cannot show commmands due to privacy
```

Am I referencing the octopilot repository incorrectly? Not that this error is occurring during the setup job phase of the action
